openapi: 3.0.0
paths:
  /api:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
info:
  title: OURTIME API
  description: OURTIME API DOCUMENTATION
  version: '0.1'
  contact: {}
tags: []
servers:
  - url: http://localhost:3100
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas: {}
